### ISSUE TITLE
Swap indices

### ISSUE THREAD

**Issue by IshitaTakeshi** [IshitaTakeshi/SVMLightLoader.jl#3]
When 1000 vectors which each vector is 5 dim, and named X is given, its size(X) should be 

```
size(X) == (1000, 5)
```

in Julia. (most of modules do so)

But load_svmlight_file in SVMLightLoader.jl returns X such that 

```
size(X) == (5, 1000)
```

I think this should be fixed. 
What do you think @Evizero ?

**Comment by Evizero** [comment]
Are you talking about observations vs feature dimension?

I think the way to go for machine learning is to use the first dimension to encode the features and the second to encode observations.

So a dataset `X` of 1000 observations with 5 features each would result in

``` Julia
size(X) = (5, 1000)
```

This goes against common statistics conventions, but yields in general much better performance because of cache locality (the features of an observation are next to each other in memory because of [how Julia stores arrays](http://docs.julialang.org/en/latest/manual/performance-tips/#access-arrays-in-memory-order-along-columns)). This is especially true for support vector machines, where for most algorithm the outer loop is over the observations and the inner loop is over the features.

So I absolutely think the current way is the better way for SVMs. In fact, all ML algorithms I am and will be implementing in Julia follow these conventions because of performance reasons.

**Comment by Evizero** [comment]
If someone needs it the other way around, then performance doesn't seem to be the key issue and a simple transpose would do the trick. I think we should leave it as it is

**Comment by IshitaTakeshi** [comment]
Thanks!
